name: Deploy To Server

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  deploy_backend:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout

        uses: actions/checkout@v2

      - name: Deployment

        uses: appleboy/ssh-action@master

        with:

          host: ${{ secrets.SSH_HOST }}

          key: ${{ secrets.SSH_PRIVATE_KEY }}

          username: ${{ secrets.SSH_USERNAME }}

          port: 65333

          script: |

            cd /home/egsdrhcwhosting/public_html 

            git pull origin master

